### ISSUE TITLE
Issues with docker container not being created correctly on Jenkins build

### ISSUE THREAD

**Issue by guitaristgba247247** [UKHomeOffice/application-container-platform#527]
Hi, 

For every job runs on our Jenkins instance, we are receiving the following docker error with no response from daemon, please advise further?

Successfully built 07c6f0898fb8
Creating runinttests_mysql_1
Creating runinttests_redis_1
Creating runinttests_frontend_1
Creating runinttests_selenium_1
Creating runinttests_backend_1
Creating runinttests_waiter_1
Creating runinttests_test_1
waiting for everything to be up
**Failed to wait container (removalse2etests_waiter_1): Error response from daemon: No such container: removalse2etests_waiter_1**
Attaching to runinttests_waiter_1

https://ircbd-jenkins.ci.digital.homeoffice.gov.uk/job/runIntTests/14/consoleFull

Thanks

**Comment by oyelekci** [comment]
That particular instance was brought back online (@zuzak is aware) because a plugin update had gone awry and changed config and build XML versions from 1.0 to 1.1. So, Jenkins refused to start at all. We brought it back online by downgrading the instance itself and all its plugins. You may want to check you have all the plugins you need.

I'm afraid this is the extent of the advice we can offer you. As mentioned over Slack, Jenkins is not a tool supported on our Platform and projects that choose to diverge from the pattern we recommend need to be entirely self sufficient in troubleshooting any issues.
